name = "titanic_analysis"
description = "타이타닉 데이터 분석및 시각화_모델구축"
authors = [
    { name = "채수민", email = "suminc023@gmail.com" }
]
license = { text = "MIT" }
readme = "README.md"

pandas = "^2.2.3"
numpy = "^2.1.3"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
scikit-learn = "^1.5.2"
jupyter = "^7.2.2"

requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
